---
- name: Deploy backend nodejs service
  hosts: backend
  gather_facts: no
  
  vars:
    - deploy_dir: /var/www/concession-kiosk-backend

  vars_files:
    - .majikmike

  tasks:

  - name: Check if platform is Virtualbox
    lineinfile:
       dest: /sys/devices/virtual/dmi/id/sys_vendor
       line: "innotek GmbH"
    check_mode: yes
    register: virtualbox
    failed_when: (virtualbox is changed) or (virtualbox is failed)
    ignore_errors: true

  - name: Set fact for Virtual
    set_fact:
      physical: false
      virtual: true
    when: virtualbox

  - name: Register if system is virtualbox
    block:
      - name: Run the subscription-manager
        redhat_subscription:
          state: present
          username: "{{ rhsm_username }}"
          password: "{{ rhsm_password }}"
          pool: "{{ rhsm_pool_id }}"
        register: subs_status
    when: virtualbox


  - name: Install nodejs and git
    ansible.builtin.yum: 
      name: 
        - nodejs
        - git
      state: present

  - name: Create user kiosk
    user:
      name: kiosk
      comment: Concession Kiosk Frontend user

  - name: Create home directory for concession kiosk backend
    ansible.builtin.file:
      path: "{{ deploy_dir }}"
      owner: kiosk
      group: kiosk
      state: directory

  - name: Clone backend application
    ansible.builtin.git: 
      repo: https://github.com/itsbanjo/concession-kiosk-backend.git 
      dest: "{{ deploy_dir }}"
    become: yes
    become_user: kiosk

  - name: Open port 8080 for the application
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
      immediate: true

  - name: Disable SELinux for demo purposes
    ansible.posix.selinux:
      policy: targeted
      state: permissive

  - name: Copy backend systemd
    copy:
      src: systemd/backend.service
      dest: /lib/systemd/system/

  - name: Reload systemd
    systemd:
      daemon_reload: true

  - name: Install npm packages
    command: "npm install --quiet --silent"
    args:
      chdir: "{{ deploy_dir }}"

  - name: Start backend
    systemd:
      name: backend
      state: started
      enabled: true

  - name: Build a hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts

