template: RHEL8-U2HW14
folder: /Testing
network_vlan: VLAN100
bootstrap_foreman_fqdn: 
bootstrap_download_method: http
bootstrap_org: "IntegrateZone"
bootstrap_location: "Auckland"
bootstrap_activationkey: "RHEL8.Base"
bootstrap_login: ""
bootstrap_password: ""
bootstrap_hostgroup: "RHEL8"
bootstrap_additional_args: ""
bootstrap_target_path: /root/bootstrap.py
bootstrap_local_copy: False

