---
- name: Clone VM template 
  hosts: all
  serial: 1
  gather_facts: no
  
  vars:
    template: RHEL8-U2HW15
    bootstrap_foreman_fqdn: satellite.lab.integrate.zone
    bootstrap_download_method: http
    bootstrap_org: "IntegrateZone"
    bootstrap_location: "Auckland"
    bootstrap_activationkey: "RHEL8.Base"
    bootstrap_login: ""
    bootstrap_password: ""
    bootstrap_hostgroup: "RHEL8"
    bootstrap_additional_args: ""
    bootstrap_target_path: /root/bootstrap.py
    bootstrap_local_copy: False

  vars_files:
    - .majikmike

  tasks:

  - name: Print out vars
    debug:
      msg: "{{ inventory_hostname }}: {{ ip_address }}/{{ ip_mask }} {{ gateway }}"

  - name:  Clone a virtual machine from Linux template and customization
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      state: present
      folder: /Testing
      template: "{{ template }}"
      name: "{{ inventory_hostname }}"
      networks:
        - name: "VLAN10"
          type: static
          ip: "{{ ip_address }}"
          netmask: "{{ ip_mask }}"
          gateway: "{{ gateway }}"
          start_connected: yes
          connected: yes
      wait_for_ip_address: true
      customization:
        hostname: "{{ inventory_hostname }}"
        domain: "{{ domain }}"
        dns_servers:
          - 192.168.2.105
        dns_suffix:
          - lab.integrate.zone
    delegate_to: localhost
    register: newvm

  - name: download bootstrap.py from {{ bootstrap_foreman_fqdn }}
    get_url:
      dest: "{{ bootstrap_target_path }}"
      url: "{{ bootstrap_download_method }}://{{ bootstrap_foreman_fqdn }}/pub/bootstrap.py"
    when: not bootstrap_local_copy

  - name: copy bootstrap.py from local machine
    copy:
      dest: "{{ bootstrap_target_path }}"
      src: bootstrap.py
    when: bootstrap_local_copy

  - name: generate bootstrap.py arguments
    set_fact:
      bootstrap_args: "--server {{ bootstrap_foreman_fqdn }} --organization '{{ bootstrap_org }}' --location '{{ bootstrap_location }}' --activationkey '{{ bootstrap_activationkey }}' --download-method {{ bootstrap_download_method }}"
      bootstrap_foreman_args: "{% if bootstrap_password != '' %}--login '{{ bootstrap_login }}' --password '{{ bootstrap_password }}' --hostgroup '{{ bootstrap_hostgroup }}'{% else %}--skip foreman{% endif %}"

  - name: run bootstrap.py
    command: "/usr/libexec/platform-python {{ bootstrap_target_path }} {{ bootstrap_args }} {{ bootstrap_foreman_args }} {{ bootstrap_additional_args }} --force "

  - name: remove bootstrap.py
    file:
      path: "{{ bootstrap_target_path }}"
